app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/',                                                                 'PromemoriaController@indexToday');

Route::get( '/clienti',                                                         'ClientiController@index');
Route::get( '/clienti/new',                                                     'ClientiController@create');
Route::get( '/clienti/{cliente}/edit',                                          'ClientiController@edit');
Route::get( '/clienti/{cliente}',                                               'ClientiController@show');
Route::post('/clienti',                                                         'ClientiController@store');
Route::post('/clienti/filter',                                                  'ClientiController@filter');
Route::put( '/clienti/{cliente}',                                               'ClientiController@update');
Route::put( '/clienti/{cliente}/importante',                                    'ClientiController@toggleImportante');
Route::delete( '/clienti/{cliente}',                                            'ClientiController@destroy');



Route::get( '/pratiche',                                                        'PraticheController@index');
Route::get( '/clienti/{cliente}/pratiche/new',                                  'PraticheController@create');
Route::get( '/clienti/{cliente}/pratiche/{pratica}/edit',                       'PraticheController@edit');
Route::get( '/clienti/{cliente}/pratiche/{pratica}',                            'PraticheController@show');
Route::post('/clienti/{cliente}/pratiche',                                      'PraticheController@store');
Route::post('/pratiche/filter',                                                 'PraticheController@filter');
Route::put( '/clienti/{cliente}/pratiche/{pratica}',                            'PraticheController@update');
Route::delete( '/clienti/{cliente}/pratiche/{pratica}',                         'PraticheController@destroy');



Route::get( '/filiali/{filiale}/documenti/new',                                 'DocumentiController@create');
Route::get( '/clienti/{cliente}/pratiche/{pratica}/documenti/{documento}',      'DocumentiController@show');
Route::post('/filiali/{filiale}/documenti',                                     'DocumentiController@store');
Route::delete('/clienti/{cliente}/pratiche/{pratica}/documenti/{documento}',    'DocumentiController@destroy');




Route::get( '/login',                                                           'Auth\AuthController@showLoginForm');
Route::get( '/logout',                                                          'Auth\AuthController@logout');
Route::post('/login',                                                           'Auth\AuthController@login');



Route::get( '/clienti/{cliente}/pratiche/{pratica}/assegni/new',                'AssegniController@create');
Route::get( '/clienti/{cliente}/pratiche/{pratica}/assegni/{assegno}/edit',     'AssegniController@edit');
Route::post('/clienti/{cliente}/pratiche/{pratica}/assegni/',                   'AssegniController@store');
Route::put( '/clienti/{cliente}/pratiche/{pratica}/assegni/{assegno}',          'AssegniController@update');
Route::delete( '/clienti/{cliente}/pratiche/{pratica}/assegni/{assegno}',       'AssegniController@destroy');



Route::get( '/clienti/{cliente}/pratiche/{pratica}/prestazioni_mediche/new',                                'PrestazioniMedicheController@create');
Route::get( '/clienti/{cliente}/pratiche/{pratica}/prestazioni_mediche/{prestazione_medica}/edit',          'PrestazioniMedicheController@edit');
Route::post('/clienti/{cliente}/pratiche/{pratica}/prestazioni_mediche/',                                   'PrestazioniMedicheController@store');
Route::put( '/clienti/{cliente}/pratiche/{pratica}/prestazioni_mediche/{prestazione_medica}',               'PrestazioniMedicheController@update');
Route::put( '/clienti/{cliente}/pratiche/{pratica}/prestazioni_mediche/{prestazione_medica}/toggleSospeso', 'PrestazioniMedicheController@toggleSospeso');
Route::delete( '/clienti/{cliente}/pratiche/{pratica}/prestazioni_mediche/{prestazione_medica}',            'PrestazioniMedicheController@destroy');


Route::get( '/filiali/{filiale}/agenda',                                        'PromemoriaController@indexToday');
Route::get( '/filiali/{filiale}/agendaEstesa',                                  'PromemoriaController@indexAll');
Route::post('/agenda/confermaLettura',                                          'PromemoriaController@confermaLettura');
Route::post( '/filiali/{filiale}/agenda/filter',                                'PromemoriaController@filter');
Route::post('/clienti/{cliente}/pratiche/{pratica}/promemoria/new',             'PromemoriaController@store');
Route::put( '/clienti/{cliente}/pratiche/{pratica}/promemoria/{promemoria}',    'PromemoriaController@update');
Route::delete('/clienti/{cliente}/pratiche/{pratica}/promemoria/{promemoria}',  'PromemoriaController@destroy');


Route::get( '/filiali',                                                         'FilialiController@index');
Route::get( '/filiali/new',                                                     'FilialiController@create');
Route::get( '/filiali/{filiale}/edit',                                          'FilialiController@edit');
Route::put( '/filiali/{filiale}/toggleEnabled',                                 'FilialiController@toggleEnabled');
Route::put( '/filiali/{filiale}/toggleCanGenerateLetters',                      'FilialiController@toggleCanGenerateLetters');
Route::put( '/filiali/{filiale}',                                               'FilialiController@update');
Route::post( '/filiali/',                                                       'FilialiController@store');



Route::get( '/filiali/{filiale}/pannello',                                      'PannelloFilialeController@home');
Route::get( '/filiali/{filiale}/pannello/liquidato_omnia',                      'PannelloFilialeController@liquidatoOmnia');
Route::get( '/filiali/{filiale}/pannello/importo_sospeso',                      'PannelloFilialeController@importoSospeso');
Route::get( '/filiali/{filiale}/pannello/parcella_presunta',                    'PannelloFilialeController@parcellaPresunta');
Route::get( '/filiali/{filiale}/pannello/onorari',                              'PannelloFilialeController@onorari');
Route::get( '/filiali/{filiale}/pannello/sospesi_medici',                       'PannelloFilialeController@sospesiMedici');
Route::get( '/filiali/{filiale}/pannello/fatture',                              'PannelloFilialeController@fatture');




Route::get( '/clienti/{cliente}/pratiche/{pratica}/lettere/{lettera}',          'LettereController@show');
Route::get( '/clienti/{cliente}/pratiche/{pratica}/lettere/',                   'LettereController@showOptions');


Route::get( '/clienti/{cliente}/pratiche/{pratica}/fatture/new',                'FattureController@create');
Route::get( '/clienti/{cliente}/pratiche/{pratica}/fatture/{fattura}',          'FattureController@show');
Route::get( '/clienti/{cliente}/pratiche/{pratica}/fatture/{fattura}/edit',     'FattureController@edit');
Route::put( '/clienti/{cliente}/pratiche/{pratica}/fatture/{fattura}',          'FattureController@update');
Route::post('/clienti/{cliente}/pratiche/{pratica}/fatture/',                   'FattureController@store');
Route::delete( '/clienti/{cliente}/pratiche/{pratica}/fatture/{fattura}',       'FattureController@destroy');

app/Fattura.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Fattura extends Model
{
    protected $table = 'fatture';
    
    /**
     *  Ritorna la pratica relativa al documento
     */
    public function pratica()
    {
        return $this->belongsTo('\App\Pratica', 'pratica_id');
    }
    
    public function getIvaAttribute()
    {
        return $this->importo_netto * 0.22;
    }
    
    public function getLordoCompetenzeAttribute()
    {
        return $this->importo_netto + $this->iva;
    }
    
    public function getLordoIncassatoAttribute()
    {
        return $this->lordo_competenze + $this->importo_esente;
    }
    
    
    public function getNomeFilialeAttribute()
    {
        switch($this->appartenenza)
        {
            case 1: return 'Ely\'s';
            case 2: return 'Elisir';
            case 3: return 'Ely\'s Elisir Group';
            default: return '';
        }
    }
    
    // Mutator data_emissione
    public function setDataEmissioneAttribute($value)
    {
        if (is_string($value) && $value !== '')
            $this->attributes['data_emissione'] = \Carbon\Carbon::createFromFormat('d/m/Y', $value);
        else if ($value === '')
            $this->attributes['data_emissione'] = null;
        else
            $this->attributes['data_emissione'] = $value;
    }
    
    // Form Accessor data_emissione
    public function formDataEmissioneAttribute($value)
    {
        return format_date($value);
    }
    
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [ 'numero',
                            'dettaglio_prestazione',
                            'data_emissione',
                            'importo_netto',
                            'importo_esente',
                            'appartenenza'];
                            
    protected $dates = [ 'created_at', 'data_emissione'];

}

app/Http/Controllers/PannelloFilialeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;


class PannelloFilialeController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('conferma-promemoria');
    }
    
    public function home(Request $request, $filiale_id)
    {
        $filiale = \App\Filiale::findOrFail($filiale_id);
        
        if($request->user()->cannot('visualizzare-pannello-filiale', $filiale)) {
            // L'utente non puo' visualizzare il pannello filiale di altre filiali
            abort(403);
        }
        
        $filiali = \App\Filiale::all();
        return view('pannello_filiale.home', compact('filiale', 'filiali'));
    }

    public function liquidatoOmnia(Request $request, $filiale_id)
    {
        $filiale = \App\Filiale::findOrFail($filiale_id);
        
        if($request->user()->cannot('visualizzare-pannello-filiale', $filiale)) {
            // L'utente non puo' visualizzare il pannello filiale di altre filiali
            abort(403);
        }
        
        $pratiche_query = \App\Pratica::whereHas('cliente', function($query) use ($filiale_id) {
            $query->where('filiale_id', $filiale_id);
        })->whereIn('stato_pratica', [0, 3])
          ->where('liquidato_omnia', '>', 0)
          ->orderBy('numero_pratica', 'desc'); //stato pratica: aperte o ss. legale
        
        $pratiche_query = $this->filtraPratiche($request, $pratiche_query);
        $pratiche = $pratiche_query->get();
        
        $filiali = \App\Filiale::all();
        
        return view('pannello_filiale.liquidato_omnia', compact('filiale', 'filiali', 'pratiche', 'request'));
    }
    
    public function importoSospeso(Request $request, $filiale_id)
    {
        $filiale = \App\Filiale::findOrFail($filiale_id);
        
        if($request->user()->cannot('visualizzare-pannello-filiale', $filiale)) {
            // L'utente non puo' visualizzare il pannello filiale di altre filiali
            abort(403);
        }
        
        $pratiche_query = \App\Pratica::whereHas('cliente', function($query) use ($filiale_id) {
            $query->where('filiale_id', $filiale_id);
        })->whereIn('stato_pratica', [0, 3])
          ->where('importo_sospeso', '>', 0)
          ->orderBy('numero_pratica', 'desc'); //stato pratica: aperte o ss. legale

        $pratiche_query = $this->filtraPratiche($request, $pratiche_query);
        $pratiche = $pratiche_query->get();
        
        $filiali = \App\Filiale::all();
        
        return view('pannello_filiale.importo_sospeso', compact('filiale', 'filiali', 'pratiche', 'request'));
    }
    
    public function parcellaPresunta(Request $request, $filiale_id)
    {
        $filiale = \App\Filiale::findOrFail($filiale_id);
        
        if($request->user()->cannot('visualizzare-pannello-filiale', $filiale)) {
            // L'utente non puo' visualizzare il pannello filiale di altre filiali
            abort(403);
        }
        
        $pratiche_query = \App\Pratica::whereHas('cliente', function($query) use ($filiale_id) {
            $query->where('filiale_id', $filiale_id);
        })->whereIn('stato_pratica', [0, 3])
          ->where('parcella_presunta', '>', 0)
          ->orderBy('numero_pratica', 'desc'); //stato pratica: aperte o ss. legale
        
        $pratiche_query = $this->filtraPratiche($request, $pratiche_query);
        $pratiche = $pratiche_query->get();
        
        
        $filiali = \App\Filiale::all();
        
        return view('pannello_filiale.parcella_presunta', compact('filiale', 'filiali', 'pratiche', 'request'));
    }
    
    public function onorari(Request $request, $filiale_id)
    {
        $filiale = \App\Filiale::findOrFail($filiale_id);
        
        if($request->user()->cannot('visualizzare-pannello-filiale', $filiale)) {
            // L'utente non puo' visualizzare il pannello filiale di altre filiali
            abort(403);
        }
        
        $pratiche_query = \App\Pratica::whereHas('cliente', function($query) use ($filiale_id) {
            $query->where('filiale_id', $filiale_id);
        })->whereIn('stato_pratica', [0, 3])
          ->where('onorari', '>', 0)
          ->orderBy('numero_pratica', 'desc'); //stato pratica: aperte o ss. legale
        
        $pratiche_query = $this->filtraPratiche($request, $pratiche_query);
        $pratiche = $pratiche_query->get();

        $filiali = \App\Filiale::all();
        
        return view('pannello_filiale.onorari', compact('filiale', 'filiali', 'pratiche', 'request'));
    }
    
    public function sospesiMedici(Request $request, $filiale_id)
    {
        $filiale = \App\Filiale::findOrFail($filiale_id);
        
        if($request->user()->cannot('visualizzare-pannello-filiale', $filiale)) {
            // L'utente non puo' visualizzare il pannello filiale di altre filiali
            abort(403);
        }
        
        $prestazioni = \App\PrestazioneMedica::whereHas('pratica.cliente', function($query) use ($filiale_id) {
            $query->where('filiale_id', $filiale_id);
        })->where('percentuale', '>', 0) // in convenzione
          ->where('sospeso', '=', true) // sospese
          ->whereHas('pratica', function($query) use ($request) {
            $this->filtraPratiche($request, $query);    
        })->orderBy('pratica_id', 'desc')->get();
        
        
        $filiali = \App\Filiale::all();

        return view('pannello_filiale.sospesi_medici', compact('filiale', 'filiali', 'prestazioni', 'request'));
    }
    
    public function fatture(Request $request, $filiale_id)
    {
        $filiale = \App\Filiale::findOrFail($filiale_id);
        
        if($request->user()->cannot('generare-fatture')) {
            abort(403);
        }
        
        $fattureElys = \App\Fattura::where('appartenenza', 1)->orderBy('numero')->get();
        $fattureElisir = \App\Fattura::where('appartenenza', 2)->orderBy('numero')->get();
        
        $filiali = \App\Filiale::all();
        
        return view('pannello_filiale.fatture', compact('fattureElys', 'fattureElisir', 'filiali', 'filiale'));
    }
    
    private function filtraPratiche(Request $request, $pratiche_query) {
        $numero_pratica_gt = $request->numero_pratica_gt;
        $numero_pratica_lt = $request->numero_pratica_lt;

        if ($numero_pratica_gt != NULL && $numero_pratica_lt != NULL) {
            // sono entrambi con valore
            $pratiche_query = $pratiche_query->whereBetween('numero_pratica', [$numero_pratica_gt, $numero_pratica_lt]);
        } else if ($numero_pratica_gt != NULL) {
            $pratiche_query = $pratiche_query->where('numero_pratica', '>=', $numero_pratica_gt);
        } else if ($numero_pratica_lt != NULL) {
            $pratiche_query = $pratiche_query->where('numero_pratica', '<=', $numero_pratica_lt);
        }
        
        $mese_apertura = $request->mese_apertura;
        if ($mese_apertura != NULL) {
            list($mese, $anno) = explode('/', $mese_apertura);
            $pratiche_query = $pratiche_query->whereMonth('data_apertura', '=', $mese)
                                             ->whereYear('data_apertura', '=', $anno);
        }
        
        return $pratiche_query;
    }
}

resources/views/pannello_filiale/_dashboard.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <!-- Mostra pulsanti navigazione -->
        <div class="page-header">
            <h1 class="text-center">
                Pannello Filiale
            </h1>
            <div>
                <div class="pull-left">
                </div>
                <div class="pull-right">
                    @include ('common._dropdown_selezione_filiale')
                </div>
            </div>
        </div>
    </div>
        
    <div class="container-fluid">
        <div class="col-md-2 sidebar bg-faded">
            <ul class="nav nav-pills nav-stacked">
                <li class="nav-item{{ (isset($active) && $active === 'onorari') ? ' active' : '' }}">
                    <a class="nav-link" href="{{ action('PannelloFilialeController@onorari', ['filiale' => $filiale]) }}">
                        Onorari
                    </a>
                </li>
                <li class="nav-item{{ (isset($active) && $active === 'liquidato_omnia') ? ' active' : '' }}">
                    <a class="nav-link" href="{{ action('PannelloFilialeController@liquidatoOmnia', ['filiale' => $filiale]) }}">
                        Liquidato omnia
                    </a>
                </li>
                <li class="nav-item{{ (isset($active) && $active === 'importo_sospeso') ? ' active' : '' }}">
                    <a class="nav-link" href="{{ action('PannelloFilialeController@importoSospeso', ['filiale' => $filiale]) }}">
                        Importo sospeso
                    </a>
                </li>
                <li class="nav-item{{ (isset($active) && $active === 'parcella_presunta') ? ' active' : '' }}">
                    <a class="nav-link" href="{{ action('PannelloFilialeController@parcellaPresunta', ['filiale' => $filiale]) }}">
                        Parcella presunta
                    </a>
                </li>
                <li class="nav-item{{ (isset($active) && $active === 'sospesi_medici') ? ' active' : '' }}">
                    <a class="nav-link" href="{{ action('PannelloFilialeController@sospesiMedici', ['filiale' => $filiale]) }}">
                        Sospesi medici
                    </a>
                </li>
                @can('generare-fatture')
                    <li class="nav-item{{ (isset($active) && $active === 'fatture') ? ' active' : '' }}">
                        <a class="nav-link" href="{{ action('PannelloFilialeController@fatture', ['filiale' => $filiale]) }}">
                            Fatture
                        </a>
                    </li>
                @endcan
            </ul>
        </div>

        <main class="col-md-8">
            @include('common._barra_filiale')
            
            @yield('inner-content')
        </main>
    </div>
@endsection

resources/views/pannello_filiale/_pannello_ricerca.blade.php
<div class="panel panel-default">
    <div class="panel-body">
        {!! Form::open([url()->current(), 'method' => 'GET', 'class' => 'form-horizontal']) !!}
            <div class="form-group">
                <div class="col-md-2 text-right">
                    {!! Form::label('numero_pratica', "Numero Pratica" , ['class' => 'control-label']) !!}
                </div>
                <div class="col-md-2">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-fw fa-chevron-right"></i></span>
                        {!! Form::number('numero_pratica_gt', $request->numero_pratica_gt, ['class' => 'form-control']) !!}
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-fw fa-chevron-left"></i></span>
                        {!! Form::number('numero_pratica_lt', $request->numero_pratica_lt, ['class' => 'form-control']) !!}
                    </div>
                </div>
                <div class="col-md-2 text-right">
                    {!! Form::label('mese_apertura', "Mese di apertura" , ['class' => 'control-label']) !!}
                </div>
                <div class="col-md-2">
                    <div class="input-group date month">
                        {!! Form::text('mese_apertura', $request->mese_apertura, ['class' => 'form-control date-control']) !!}
                        <span class="input-group-addon"><i class="fa fa-fw fa-calendar"></i></span>
                    </div>
                </div>
                <div class="col-md-2">
                    <button class="btn btn-primary">
                        <i class="fa fa-fw fa-search"></i>
                    </button>
                    <a class="btn btn-default" href="{{ url()->current() }}">
                        <i class="fa fa-fw fa-times"></i>
                    </a>
                </div>
            </div>
        {!! Form::close() !!}
    </div>
</div>

resources/views/pannello_filiale/fatture.blade.php
@extends('pannello_filiale._dashboard', ['active' => 'fatture'])
@section('inner-content')

@include('common._modal_elimina',
       ['resource' => 'fattura',
        'message' => 'Sei sicuro di voler eliminare la fattura? Questa operazione non potrà essere annullata.'])

<div class="panel panel-default">
    <div class="panel-body">
        <!-- Lista fatture Elys -->
        <h4>Fatture Elys</h4>
        <table class="table table-hover table-striped">
            <thead>
                <th>Filiale</th>
                <th>Numero fattura</th>
                <th>Numero pratica</th>
                <th>Dettaglio prestazione</th>
                <th>Importo netto</th>
                <th>Importo esente</th>
                <th>Lordo incassato</th>
                <th>Data emissione</th>
                <th>&nbsp;</th>
            </thead>
            <tbody>
                @foreach ($fattureElys as $fattura)
                    <tr class="">
                        <td class="table-text"><div>{{ $fattura->appartenenza == 1 ? 'Ely\'s' : 'Elisir' }}</div></td>
                        <td class="table-text"><div>{{ $fattura->numero }}</div></td>
                        <td class="table-text">
                            <a href="{{ action('PraticheController@show',
                                ['cliente' => $fattura->pratica->cliente, 'pratica' => $fattura->pratica])}}">
                                <div>{{ $fattura->pratica->numero_pratica }}</div>    
                            </a>
                        </td>
                        <td class="table-text"><div>{{ $fattura->dettaglio_prestazione }}</div></td>
                        <td class="table-text"><div>{{ format_money($fattura->importo_netto) }}</div></td>
                        <td class="table-text"><div>{{ format_money($fattura->importo_esente) }}</div></td>
                        <td class="table-text"><div>{{ format_money($fattura->lordo_incassato) }}</div></td>
                        
                        <td class="table-text">{{ format_date($fattura->data_emissione) }}</td>
                        
                        <td class="table-text col-md-2">
                            <a href="{{ action('FattureController@show',
                                ['cliente' => $fattura->pratica->cliente, 'pratica' => $fattura->pratica, 'fattura' => $fattura]) }}"
                                class="btn btn-default">
                                <i class="fa fa-fw fa-eye"></i>
                            </a>
                            
                            <a href="{{ action('FattureController@edit',
                                    ['cliente' => $fattura->pratica->cliente, 'pratica' => $fattura->pratica, 'fattura' => $fattura]) }}"
                                    class="btn btn-primary">
                                    <i class="fa fa-fw fa-pencil"></i>
                            </a>
                            
                            <a href="#" class="btn btn-danger showFatturaDestroyModal"
                                    data-toggle="modal" data-target="#fatturaDestroyModal" data-fattura="{{$fattura->id}}">
                                <i class="fa fa-fw fa-trash"></i>
                            </a>
                            
                            {{ Form::open(['action' => ['FattureController@destroy', 'cliente' => $fattura->pratica->cliente,
                                           'pratica' => $fattura->pratica, 'fattura' => $fattura], 'method' => 'delete', 'style' => 'display:inline;',
                                           'id' => "fattura{$fattura->id}DestroyForm"]) }}
                            {{ Form::close() }}
                        </td>
                    </tr>
                @endforeach
                <tr class="row-subtotal orange">
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th>{{ format_money($fattureElys->sum('importo_netto')) }}</th>
                    <th>{{ format_money($fattureElys->sum('importo_esente')) }}</th>
                    <th>{{ format_money($fattureElys->sum('lordo_incassato')) }}</th>
                    <th></th>
                    <th>&nbsp;</th>
                </tr>
            </tbody>
        </table>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-body">
        <!-- Lista fatture Elisir -->
        <h4>Fatture Elisir</h4>
        <table class="table table-hover table-striped">
            <thead>
                <th>Filiale</th>
                <th>Numero fattura</th>
                <th>Numero pratica</th>
                <th>Dettaglio prestazione</th>
                <th>Importo netto</th>
                <th>Importo esente</th>
                <th>Lordo incassato</th>
                <th>Data emissione</th>
                <th>&nbsp;</th>
            </thead>
            <tbody>
                @foreach ($fattureElisir as $fattura)
                    <tr class="">
                        <td class="table-text"><div>{{ $fattura->appartenenza == 1 ? 'Ely\'s' : 'Elisir' }}</div></td>
                        <td class="table-text"><div>{{ $fattura->numero }}</div></td>
                        <td class="table-text">
                            <a href="{{ action('PraticheController@show',
                                ['cliente' => $fattura->pratica->cliente, 'pratica' => $fattura->pratica])}}">
                                <div>{{ $fattura->pratica->numero_pratica }}</div>    
                            </a>
                        </td>
                        <td class="table-text"><div>{{ $fattura->dettaglio_prestazione }}</div></td>
                        <td class="table-text"><div>{{ format_money($fattura->importo_netto) }}</div></td>
                        <td class="table-text"><div>{{ format_money($fattura->importo_esente) }}</div></td>
                        <td class="table-text"><div>{{ format_money($fattura->lordo_incassato) }}</div></td>
                        
                        <td class="table-text">{{ format_date($fattura->data_emissione) }}</td>
                        
                        <td class="table-text col-md-2">
                            <a href="{{ action('FattureController@show',
                                ['cliente' => $fattura->pratica->cliente, 'pratica' => $fattura->pratica, 'fattura' => $fattura]) }}"
                                class="btn btn-default">
                                <i class="fa fa-fw fa-eye"></i>
                            </a>
                            <a href="{{ action('FattureController@edit',
                                    ['cliente' => $fattura->pratica->cliente, 'pratica' => $fattura->pratica, 'fattura' => $fattura]) }}"
                                    class="btn btn-primary">
                                    <i class="fa fa-fw fa-pencil"></i>
                            </a>
                            
                            <a href="#" class="btn btn-danger showFatturaDestroyModal"
                                    data-toggle="modal" data-target="#fatturaDestroyModal" data-fattura="{{$fattura->id}}">
                                <i class="fa fa-fw fa-trash"></i>
                            </a>
                            
                            {{ Form::open(['action' => ['FattureController@destroy', 'cliente' => $fattura->pratica->cliente,
                                           'pratica' => $fattura->pratica, 'fattura' => $fattura], 'method' => 'delete', 'style' => 'display:inline;',
                                           'id' => "fattura{$fattura->id}DestroyForm"]) }}
                            {{ Form::close() }}
                        </td>
                    </tr>
                @endforeach
                <tr class="row-subtotal orange">
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th>{{ format_money($fattureElisir->sum('importo_netto')) }}</th>
                    <th>{{ format_money($fattureElisir->sum('importo_esente')) }}</th>
                    <th>{{ format_money($fattureElisir->sum('lordo_incassato')) }}</th>
                    <th></th>
                    <th>&nbsp;</th>
                </tr>
            </tbody>
        </table>
    </div>
</div>

@endsection

resources/views/pannello_filiale/home.blade.php
@extends('pannello_filiale._dashboard')
@section('inner-content')
@endsection

resources/views/pannello_filiale/importo_sospeso.blade.php
@extends('pannello_filiale._dashboard', ['active' => 'importo_sospeso'])
@section('inner-content')

@include('pannello_filiale._resoconto_pratiche', ['nome_campo' => 'importo_sospeso', 'nome_campo_h' => 'Importo Sospeso'])

@endsection

resources/views/pannello_filiale/liquidato_omnia.blade.php
@extends('pannello_filiale._dashboard', ['active' => 'liquidato_omnia'])
@section('inner-content')

@include('pannello_filiale._resoconto_pratiche', ['nome_campo' => 'liquidato_omnia', 'nome_campo_h' => 'Liquidato Omnia'])

@endsection

resources/views/pannello_filiale/onorari.blade.php
@extends('pannello_filiale._dashboard', ['active' => 'onorari'])
@section('inner-content')

@include('pannello_filiale._resoconto_pratiche', ['nome_campo' => 'onorari', 'nome_campo_h' => 'Onorari'])

@endsection